  export const areaInfo = state => state.areaInfo
  export const secAreaList = state => state.secAreaList
  export const areaList = state => state.areaList
  export const searchPaneShow = state => state.searchPaneShow
  export const searchParams = state => state.searchParams
  export const searchList = state => state.searchList
  export const areaInfoData = state => state.areaInfoData
  export const areaInfoList = state => state.areaInfoList
  export const activeAreaInfoList = state => state.activeAreaInfoList
  export const tableMenuPaneShow = state => state.tableMenuPaneShow
  export const reportFormShow = state => state.reportFormShow
  export const reportFormData = state => state.reportFormData
  export const areaCodeAndDataId = state => state.areaCodeAndDataId
  export const searchItemMacroList = state => state.searchItemMacroList
  export const uuidClickedInfo = state => state.uuidClickedInfo
  export const measureNum = state => state.measureNum
  export const areaReportFormShow = state => state.areaReportFormShow
  export const searchAroundShow = state => state.searchAroundShow
  export const topicList = state => state.topicList
  export const topicListShow = state => state.topicListShow
  export const areaDetailInfo = state => state.areaDetailInfo
  export const userinfo = state => state.userinfo
  export const mapJsonAndImg = state => state.mapJsonAndImg
  export const layerIdList = state => state.layerIdList