/* SOURCE */
export const REQUEST_SOURCE_START = 'REQUEST_SOURCE_START'
export const REQUEST_SOURCE_END = 'REQUEST_SOURCE_END'
export const LOAD_SOURCE = 'LOAD_SOURCE'
export const UPDATE_ACTIVE_SOURCE = 'UPDATE_ACTIVE_SOURCE'

/* STYLE */
export const REQUEST_STYLE_START = 'REQUEST_STYLE_START'
export const REQUEST_STYLE_END = 'REQUEST_STYLE_END'
export const LOAD_STYLE = 'LOAD_STYLE'

/* MAP */
export const SET_MAIN_MAP = 'SET_MAIN_MAP'

export const SEARCH_PANE_IS_SHOW = 'SEARCH_PANE_IS_SHOW'

export const TABLE_PANE_SHOW = 'TABLE_PANE_SHOW'

export const SEARCH_PARAMS = 'SEARCH_PARAMS'

export const GET_SEARCH_RESULT = 'GET_SEARCH_RESULT'

export const GET_AREA_DATA = 'GET_AREA_DATA'

export const SET_AREA_LIST = 'SET_AREA_LIST'

export const SET_SEC_AREA_LIST = 'SET_SEC_AREA_LIST'

export const SET_AREA_DETAIL_INFO = 'SET_AREA_DETAIL_INFO'

export const SET_ACTIVE_AREA_LIST = 'SET_ACTIVE_AREA_LIST'

export const MODIFY_AREA_INFO_LIST = 'MODIFY_AREA_INFO_LIST'

export const SET_LEFT_ACTIVE_AREA_LIST = 'SET_LEFT_ACTIVE_AREA_LIST'

export const SET_AREA_INFO = 'SET_AREA_INFO'

export const SET_SEARCH_MACRO_LIST = 'SET_SEARCH_MACRO_LIST'

export const SET_SELECTED_AREA_LIST = 'SET_SELECTED_AREA_LIST'

export const SET_AREACODE_AND_DATAID = 'SET_AREACODE_AND_DATA'

export const SET_REPORT_FORM_SHOW = 'SET_REPORT_FORM_SHOW'

export const SET_REPORT_FORM_DATA = 'SET_REPORT_FORM_DATA'

export const CLEAR_REPORT_FORM = 'CLEAR_REPORT_FORM'

export const SET_MEASURE_NUM = 'SET_MEASURE_NUM'

export const SET_UUID_INFO = 'SET_UUID_INFO'

export const SET_AREA_REPORT_FORM_SHOW = 'SET_AREA_REPORT_FORM_SHOW'

export const SET_SEARCH_AROUND_SHOW = 'SET_SEARCH_AROUND_SHOW'

export const SET_TOPIC_LIST = 'SET_TOPIC_LIST'

export const SET_TOPIC_LIST_SHOW = 'SET_TOPIC_LIST_SHOW'

export const ADD_TOURSIM_LAYER = 'ADD_TOURSIM_LAYER'

export const SET_USER_INFO = 'SET_USER_INFO'

export const ADD_PROVERTY_AREA_LAYER = 'ADD_PROVERTY_AREA_LAYER'

export const ADD_LAYER_ID_LIST = 'ADD_LAYER_ID_LIST'

export const SET_MAP_JSON_AND_IMG = 'SET_MAP_JSON_AND_IMG'

export const SET_REPORT_FORM_TYPE = 'SET_REPORT_FORM_TYPE'

export const SET_URL_PATH = 'SET_URL_PATH'

export const SET_LAYER_CONTROL_SHOW = 'SET_LAYER_CONTROL_SHOW'

export const SET_DRAW_PANEL_TYPE = 'SET_DRAW_PANEL_TYPE'