/* SOURCE */
export const REQUEST_SOURCE_START = 'REQUEST_SOURCE_START'
export const REQUEST_SOURCE_END = 'REQUEST_SOURCE_END'
export const LOAD_SOURCE = 'LOAD_SOURCE'
export const UPDATE_ACTIVE_SOURCE = 'UPDATE_ACTIVE_SOURCE'

/* STYLE */
export const REQUEST_STYLE_START = 'REQUEST_STYLE_START'
export const REQUEST_STYLE_END = 'REQUEST_STYLE_END'
export const LOAD_STYLE = 'LOAD_STYLE'

/* MAP */
export const SET_MAIN_MAP = 'SET_MAIN_MAP'

export const SEARCH_PANE_IS_SHOW = 'SEARCH_PANE_IS_SHOW'

export const SEARCH_PARAMS = 'SEARCH_PARAMS'

export const GET_SEARCH_RESULT = 'GET_SEARCH_RESULT'
